name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
     -
        name: Checkout
        uses: actions/checkout@v2
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
     -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
       with:
          images: simonmcnair/ddns
      
     - name: Build and push Docker image
       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
       with:
          context: .
#          file: build/Dockerfile.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



#    - name: Build Docker4
#      uses: mr-smithers-excellent/docker-build-push@v5
#      with:
##         image: simonmcnair/ddns
 #        registry: docker.io
#         dockerfile: build/Dockerfile.
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

     # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
         echo Add other actions to build,
         echo test, and deploy your project.
