name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build --tag my-image-name:$(date +%s) build

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2

     # Runs a single command using the runners shell
#    - name: Run a one-line script
#      run: |
#         echo Hello, world !
#         echo ${{ secrets.DOCKER_USERNAME }}
#         echo ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
          images: simonmcnair/ddns
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
          context: .
#          file: build/Dockerfile.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



#    - name: Build Docker4
#      uses: mr-smithers-excellent/docker-build-push@v5
#      with:
##         image: simonmcnair/ddns
 #        registry: docker.io
#         dockerfile: build/Dockerfile.
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

     # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
         echo Add other actions to build,
         echo test, and deploy your project.
